package com.example.miaosha.dao;

import com.example.miaosha.dto.ItemStockDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ItemStockDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int insert(ItemStockDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int insertSelective(ItemStockDto record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount")Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    ItemStockDto selectByPrimaryKey(Integer id);

    ItemStockDto selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int updateByPrimaryKeySelective(ItemStockDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int updateByPrimaryKey(ItemStockDto record);
}