package com.example.miaosha.dao;

import com.example.miaosha.dto.ItemDto;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ItemDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int insert(ItemDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int insertSelective(ItemDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    ItemDto selectByPrimaryKey(Integer id);

    List<ItemDto> itemList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *|
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int updateByPrimaryKeySelective(ItemDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 16 16:03:29 CST 2022
     */
    int updateByPrimaryKey(ItemDto record);
}