package com.example.miaosha.dao;

import com.example.miaosha.dto.OrderDto;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrderDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Jun 25 14:48:03 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Jun 25 14:48:03 CST 2022
     */
    int insert(OrderDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Jun 25 14:48:03 CST 2022
     */
    int insertSelective(OrderDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Jun 25 14:48:03 CST 2022
     */
    OrderDto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Jun 25 14:48:03 CST 2022
     */
    int updateByPrimaryKeySelective(OrderDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sat Jun 25 14:48:03 CST 2022
     */
    int updateByPrimaryKey(OrderDto record);
}