package com.example.miaosha.dao;

import com.example.miaosha.dto.OrderLogDto;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface OrderLogDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Sun Jul 03 21:51:52 CST 2022
     */
    int deleteByPrimaryKey(String orderLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Sun Jul 03 21:51:52 CST 2022
     */
    int insert(OrderLogDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Sun Jul 03 21:51:52 CST 2022
     */
    int insertSelective(OrderLogDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Sun Jul 03 21:51:52 CST 2022
     */
    OrderLogDto selectByPrimaryKey(String orderLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Sun Jul 03 21:51:52 CST 2022
     */
    int updateByPrimaryKeySelective(OrderLogDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Sun Jul 03 21:51:52 CST 2022
     */
    int updateByPrimaryKey(OrderLogDto record);

    List<OrderLogDto> selectDumpedLog(@Param("curTime")Date curTime, @Param("duration")Integer duration);
}