package com.example.miaosha.dao;

import com.example.miaosha.dto.PromoDto;

public interface PromoDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 26 21:51:19 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 26 21:51:19 CST 2022
     */
    int insert(PromoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 26 21:51:19 CST 2022
     */
    int insertSelective(PromoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 26 21:51:19 CST 2022
     */
    PromoDto selectByPrimaryKey(Integer id);

    PromoDto selectByItemId(Integer itemId);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 26 21:51:19 CST 2022
     */
    int updateByPrimaryKeySelective(PromoDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Sun Jun 26 21:51:19 CST 2022
     */
    int updateByPrimaryKey(PromoDto record);
}