package com.example.miaosha.dao;

import com.example.miaosha.dto.SequenceDto;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SequenceDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Jun 25 16:05:11 CST 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Jun 25 16:05:11 CST 2022
     */
    int insert(SequenceDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Jun 25 16:05:11 CST 2022
     */
    int insertSelective(SequenceDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Jun 25 16:05:11 CST 2022
     */
    SequenceDto selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Jun 25 16:05:11 CST 2022
     */
    int updateByPrimaryKeySelective(SequenceDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sat Jun 25 16:05:11 CST 2022
     */
    int updateByPrimaryKey(SequenceDto record);
}