package com.example.miaosha.dao;

import com.example.miaosha.dto.UserDto;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jun 15 00:07:46 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jun 15 00:07:46 CST 2022
     */
    int insert(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jun 15 00:07:46 CST 2022
     */
    int insertSelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jun 15 00:07:46 CST 2022
     */
    UserDto selectByPrimaryKey(Integer id);

    UserDto selectByTelphoneUserDto(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jun 15 00:07:46 CST 2022
     */
    int updateByPrimaryKeySelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Jun 15 00:07:46 CST 2022
     */
    int updateByPrimaryKey(UserDto record);


}