package com.example.miaosha.dao;

import com.example.miaosha.dto.UserPasswordDto;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface UserPasswordDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int insert(UserPasswordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int insertSelective(UserPasswordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    UserPasswordDto selectByPrimaryKey(Integer id);

    UserPasswordDto selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int updateByPrimaryKeySelective(UserPasswordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int updateByPrimaryKey(UserPasswordDto record);
}