package com.example.miaosha.dao;

import com.example.miaosha.dto.userPasswordDto;

public interface userPasswordDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int insert(userPasswordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int insertSelective(userPasswordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    userPasswordDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int updateByPrimaryKeySelective(userPasswordDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jun 15 00:05:01 CST 2022
     */
    int updateByPrimaryKey(userPasswordDto record);
}